### ISSUE TITLE
Receiving unsupported file error

### ISSUE THREAD

**Issue by LouRiot** [bruigtp/REDCapDM#10]
Hello,
This is probably user error, but I having trouble using the redcap_data function. 
I am receiving the following error when trying to import my REDCap data from local file.

I have the R file, the DATA csv, the Data Dictionary CSV and the Event CSV in my working directory. However, when trying to import, I am receiving the following error

**Error in redcap_data(redcap_data(data_path = "/Users/Documents/REDCap_export.r",  : 
  Unsupported file format. Only R files are supported. Please specify the downloaded R file from REDCap within this argument.**

The code I am using is as follows:

redcap_data(data_path = "/Users/Documents/REDCap_export.r", 
dic_path = "/Users/Documents/REDCap_export_DataDictionary_.csv", 
event_path = "/Users/Documents/REDCap_export_DataDictionary_.csv")

Thanks in advance

**Comment by LouRiot** [comment]
Apologies, error in the above example code. Should be:
redcap_data(data_path = "/Users/Documents/REDCap_export.r",
dic_path = "/Users/Documents/REDCap_DataDictionary.csv",
event_path = "/Users/Documents/REDCap_Events.csv")

**Comment by LouRiot** [comment]
I am new to R. In all the examples provided the file ended with a lowercase r. I had to change to an upper case R.

**Comment by jcarmezim** [comment]
Hi,

Thank you for the feedback.
You were right, it was indeed a bug in the `redcap_data` function.
We have just fixed this error and committed a new version of the function to GitHub.
You can install it by running:
`remotes::install_github('bruigtp/REDCapDM')`

Thanks once again, and if you encounter any further issues, please don't hesitate to use the issues section to report them.

Best regards,
João

**Comment by LouRiot** [comment]
Hi,

When I run
remotes::install_github('bruigtp/REDCapDM’)

I get the following message:

Error in fetch(key) :
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/REDCapDM/help/REDCapDM.rdb' is corrupt

Is this an error on my end?

Thanks,

Lou


From: João Carmezim ***@***.***>
Date: Friday, 12 July 2024 at 9:08 PM
To: bruigtp/REDCapDM ***@***.***>
Cc: LouRiot ***@***.***>, State change ***@***.***>
Subject: Re: [bruigtp/REDCapDM] Receiving unsupported file error (Issue #10)

Hi,

Thank you for the feedback.
You were right, it was indeed a bug in the redcap_data function.
We have just fixed this error and committed a new version of the function to GitHub.
You can install it by running:
remotes::install_github('bruigtp/REDCapDM')

Thanks once again, and if you encounter any further issues, please don't hesitate to use the issues section to report them.

Best regards,
João

**Comment by jcarmezim** [comment]
Hi,

I think it is. I've just tried the same line of code and I successfully installed the REDCapDM package.
Try removing the package and restart your R session:
`remove.packages("REDCapDM")`

Thank you,
João
