### ISSUE TITLE
Inconsistent Naming of Checkbox Variables between API and Manual Downloads

### ISSUE THREAD

**Issue by munozedg** [bruigtp/REDCapDM#5]
**Description of the Issue:**

When obtaining data from a REDCap project, I've noticed an inconsistency in how checkbox variables are named, depending on the method used to download the data. Specifically, the naming convention differs between data obtained directly using the REDCap API (with an API key) and data downloaded manually through the REDCap project interface.

**Expected Behavior:**

For data downloaded manually from the REDCap project, checkbox variables are renamed as expected: each dichotomic variable is named with the root name plus the category's label. This naming convention is intuitive and aligns with my requirements for data processing and analysis.

**Observed Behavior:**

However, when downloading the data programmatically using the REDCap API, the checkbox variables are created differently and do not follow the aforementioned naming convention. This inconsistency poses a challenge to automating data processing workflows, as the variable names differ from expected based on the manual download method.

**Request:**

I want to request an enhancement or a fix that ensures consistent naming of checkbox variables, particularly when data is obtained via the REDCap API. The desired outcome is for the API download method to rename checkbox variables in the same way as the manual download process, appending each dichotomic variable with the root name plus the category label OR leaving the original suffix, which is based on the actual numerical code used in the original data. 

This consistency would greatly facilitate the automation of data processing and analysis workflows for users who rely on the API for data retrieval from REDCap.

Thank you for your attention to this matter. I am excited to find a solution that supports uniform naming conventions across different data download methods.

After using manually downloaded files: 
![image](https://github.com/bruigtp/REDCapDM/assets/2443361/d84dc4de-51dd-4235-8cf4-bc18cf4a4fcc)

After downloading the data using the API call:
![image](https://github.com/bruigtp/REDCapDM/assets/2443361/35c1ac47-2b78-4173-a401-445d9c24e44d)

**Comment by munozedg** [comment]
This issue occurs when downloading data through the API but not when downloading the files manually.

![image](https://github.com/bruigtp/REDCapDM/assets/2443361/afaa925b-422c-4377-9fcf-be0a7b4ee71f)

**Comment by jcarmezim** [comment]
Good morning @munozedg,
Sorry for the delayed response.
We are working on the issue and will get back to you as soon as it is resolved.
Thank you again for your feedback

**Comment by jcarmezim** [comment]
Hi @munozedg 

We attempted to replicate the same scenario, but in our case, we achieved the same result whether utilizing the API connection or employing the exported files from REDCap.

Using API:
![image](https://github.com/bruigtp/REDCapDM/assets/120713273/b1a2db2b-287d-4bb8-87e7-60c7e28a7f48)

Using exported files:
![image](https://github.com/bruigtp/REDCapDM/assets/120713273/f885dcae-dbb6-43a3-887b-ade6038ce7de)


Could you please provide us with more information about the variable in question before the transformation?

Thank you in advance.
